### ISSUE TITLE
Google Spreadsheet input: I can't see the Fields tab

### ISSUE THREAD

**Issue by anagonzalez133** [jfmonteil/Pentaho-Google-Sheet-Plugin#1]
OS: Ubuntu 16.04
Java: OpenJDK 1.8_0_201
PDI: 8.2 CE (the REMIX version from Matt Caster, with some aditional plugins and bugfixes that aren't included in the sourceforge CE version)

To install the plugin, I deleted the old version available in ~/data-integration/plugins/steps/, and unzipped the zip file in ~/data-integration/plugins (it created a new folder with the name **PentahoGoogleSheetsPlugin-3**)
I'm able to configure the Service account and the Spreadsheet, but there's no tab for the fields part

**Comment by anagonzalez133** [comment]
I've retried adding the old plugin again, but still no Fields tab. The test button does seem to work, I forgot to mention it previously, when I configured the secret it told me that the connection to Google was sucessful.

**Comment by jfmonteil** [comment]
Hello, I think I know why, I am using an old library for input fields (TextInputFields) :(
I need 2 days to fix maximum but I will be in holidays until the 21st of Feb and I need to handle kids ;)
I will try to provide a quick fix tonight (all fields retrieved), otherwise will look at it

**Comment by smalos** [comment]
Can we expect a fix by the end of this month? Thanks a lot.

**Comment by jfmonteil** [comment]
Working on it, aiming the 5th of March.
Maybe I will propose a workaround before the end of the week.
I will tell you

**Comment by jfmonteil** [comment]
Hey sorry, I need a bit more, 
Is it input or output step ? The Output step TAKES ALL fields inbound, it has no fields tab (see documentation)
Cheers !

**Comment by anagonzalez133** [comment]
Hi, the issue is with the input step.
Thanks

**Comment by jfmonteil** [comment]
Hello,
Sorry I thought It was because of the depreciated TextInputFields but no, _csv file input_ step, still uses the same...
- Does CSV File Input step works for you ?
- Could you send me the logs of Spoon when the error occures ?
- Couls you send me one or 2 screenshots ?

Cheers,
JFM

**Comment by anagonzalez133** [comment]
Sorry, there's no error message, simply the tab is not there. I'm attaching the output for where I simply open PDI, go to the step on the transformation, edit it, check that the connection works, but no tab for fields appear. https://pastebin.com/2aZYRNAD
The CSV File Input step works for me, but that step doesn't have a separate tab for fields. The Microsoft Excel Input step does have a separate tab for fields, and it works for me.
Regards

**Comment by smalos** [comment]
@anagonzalez133  Have you tried it with the latest PDI 9.1 CE?

**Comment by anagonzalez133** [comment]
> @anagonzalez133 Have you tried it with the latest PDI 9.1 CE?
@smalos  Nope, I prefer staying with the cooked 8.2 CE + some bug fixes (and convenient plugins, although I could add them to the new version) added that Matt Casters has out. I've tested that version already and right now I don't have the time to test a new version for new surprises.

**Comment by anagonzalez133** [comment]
I forgot to attach the screenshots

![20200228_001](https://user-images.githubusercontent.com/10425604/75539829-318a8580-5a1b-11ea-95ca-fb0ea525a2f1.jpg)
![20200228_002](https://user-images.githubusercontent.com/10425604/75539838-35b6a300-5a1b-11ea-906f-9c798cf8c180.jpg)
![20200228_003](https://user-images.githubusercontent.com/10425604/75539843-3818fd00-5a1b-11ea-9f42-cde237acfa81.jpg)

**Comment by jfmonteil** [comment]
Hello, I am currently changing so there is no depreciation, I am close to it, I have tested **compilation** with both 9.0 and 8.3 and 8.2 versions
In the sreenshots that you sent me you show me Google OUTPUT steps. Those steps have no _fields tab_. Only **Input** has some.

**Comment by anagonzalez133** [comment]
The Output step does works (although the check to create a new sheet if it doesn't exist doesn't work, but that's another issue to file). Here are the screenshots.
![20200228_004](https://user-images.githubusercontent.com/10425604/75557206-e8006180-5a3f-11ea-9c31-c41ba3669426.jpg)
![20200228_005](https://user-images.githubusercontent.com/10425604/75557212-ea62bb80-5a3f-11ea-9ec5-81838bde79af.jpg)

**Comment by anagonzalez133** [comment]
Sorry, I mis-read your comment and thought you were asking for screenshots of the Output step, now I see what you are saying, I just deleted my comment with the useless screenshots... And you are right (bump my head on the table) Sorry for wasting your time with a stupid error...

**Comment by anagonzalez133** [comment]
And the Input step works like a charm. Sorry again.

**Comment by jfmonteil** [comment]
No problem ! it was constructive anyway, I recoded some parts that were using depreciated Pentaho libs thanks to you, and it fixed some other parts. DO not hesitate to open new tickets if you find anything, it keeps me vigilant
