### ISSUE TITLE
"Append to sheet" setting not saved

### ISSUE THREAD

**Issue by smalos** [jfmonteil/Pentaho-Google-Sheet-Plugin#4]
If I tick "Append to sheet" and click on "OK", the checkbox is unticked when I open the output dialog again.

If both "Append to sheet" and "Create new sheet if it does not exist" are ticked, the settings are saved.

If just "Create new sheet if it does not exist" is ticked, "Append to sheet" is ticked too when I open the dialog again.

**Comment by jfmonteil** [comment]
Thanks you, Let me check this today

**Comment by jfmonteil** [comment]
Thank you ! I had left a gross bug behind. I apologize for the numerous fixes before having a clean version. 4.1 should solve the problem. Than you again for your perseverance.

**Comment by smalos** [comment]
Thanks, that fixed it!

Just a question regarding PentahoGoogleSheetsPlugin-4.1-distribution.zip :
The archive contains both PentahoGoogleSheetsPlugin-4.0.jar and PentahoGoogleSheetsPlugin-4.1.jar. I assume PentahoGoogleSheetsPlugin-4.0.jar can be removed.

**Comment by jfmonteil** [comment]
yes I have cleaned the zip ;)
