### ISSUE TITLE
Output Step missing first line

### ISSUE THREAD

**Issue by fbourgine** [jfmonteil/Pentaho-Google-Sheet-Plugin#5]
Hi,

I think I found an issue in Output step : The first data record is missing.

See following example : 

In my recordset I got 689 lines in the step "Presents_3" but only 688 in Google Spreadsheet.
To confirm I made a output copy in CSV and I got 689 lines.
In facts, the first data line is missing

![image](https://user-images.githubusercontent.com/35697727/78116048-032a0c80-7404-11ea-9c12-41ff3b72e02d.png)

![image](https://user-images.githubusercontent.com/35697727/78116073-0fae6500-7404-11ea-9e24-1b2fa09b62bf.png)

![image](https://user-images.githubusercontent.com/35697727/78116087-150baf80-7404-11ea-9f88-8e8a5c79e020.png)

**Comment by jfmonteil** [comment]
Hello,
Merci Fabrice pour votre retour : Good catch !
Correction published (did not version anything because of the marketplace)
Added a transformation to test in sample.

A bientôt,
JFM

**Comment by fbourgine** [comment]
It works well !
Thank you very much JF

Fabrice
